import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { prisma } from '../db'
import { loadProperty } from './config'
import { DETECTORS } from './detectors'
import type { PropertyConfig } from '../schemas'

/**
 * The make stage: turn scored opportunities into actions with acceptance
 * criteria, and generate the artifact each action needs.
 *
 * Two rules, both from the risk research:
 *   - generation and publication are different permissions. `review_first`
 *     properties produce drafts that wait for a human; only `auto_low_risk`
 *     properties may have reversible fixes applied automatically.
 *   - the engine never applies anything to a property it does not control
 *     (`deployAccess: false`), regardless of policy. Those actions stay
 *     `proposed` with the artifact attached for a human to ship.
 */

export interface MakeSummary {
  actionsCreated: number
  assetsGenerated: number
  applied: number
  skippedNoAccess: number
}

/** Deterministic generators. LLM-backed makers plug in at the same seam. */
const GENERATORS: Record<
  string,
  (config: PropertyConfig, context: { urls: string[] }) => { type: string; path: string; body: string }
> = {
  ship_robots_txt: (config) => ({
    type: 'technical_fix',
    path: 'robots.txt',
    body: [
      '# Generated by the Search Growth Engine.',
      '# Search and answer-engine crawlers are allowed explicitly: they are a',
      '# distinct policy surface from Googlebot, and blocking them removes the',
      '# property from AI answers without affecting classic search.',
      '',
      'User-agent: *',
      'Allow: /',
      '',
      'User-agent: OAI-SearchBot',
      'Allow: /',
      '',
      'User-agent: PerplexityBot',
      'Allow: /',
      '',
      'User-agent: Claude-SearchBot',
      'Allow: /',
      '',
      `Sitemap: https://${config.domain}/sitemap.xml`,
      '',
    ].join('\n'),
  }),

  ship_sitemap: (config, { urls }) => ({
    type: 'technical_fix',
    path: 'sitemap.xml',
    body: [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
      ...urls.map(
        (url) =>
          `  <url>\n    <loc>${url}</loc>\n    <lastmod>${new Date().toISOString().slice(0, 10)}</lastmod>\n  </url>`,
      ),
      '</urlset>',
      '',
    ].join('\n'),
  }),
}

export async function make(snapshotId: string): Promise<MakeSummary> {
  const snapshot = await prisma.snapshot.findUniqueOrThrow({ where: { id: snapshotId } })
  const config = loadProperty(snapshot.domain)

  const opportunities = await prisma.opportunity.findMany({
    where: { snapshotId },
    orderBy: { priority: 'desc' },
  })
  const pages = await prisma.page.findMany({ where: { snapshotId } })

  // Re-derive the suggested actions from the same detector run that produced
  // the opportunities, so an action can never describe work its evidence does
  // not support.
  const [evidence, clusters] = await Promise.all([
    prisma.evidence.findMany({ where: { snapshotId } }),
    prisma.queryCluster.findMany({ where: { domain: snapshot.domain } }),
  ])
  const drafts = DETECTORS.flatMap((d) => d.run({ config, evidence, pages, clusters }))

  const summary: MakeSummary = {
    actionsCreated: 0,
    assetsGenerated: 0,
    applied: 0,
    skippedNoAccess: 0,
  }

  for (const opportunity of opportunities) {
    const draft = drafts.find(
      (d) => d.title === opportunity.title && d.subject === opportunity.subject,
    )
    if (!draft) continue

    // Actions are keyed to the *finding*, not to the snapshot that observed it.
    // Opportunity rows are recreated each run (snapshots are immutable), so
    // matching on opportunityId alone would spawn a duplicate action every
    // night for a gap that has not changed — and re-open work already shipped.
    const existing = await prisma.action.findFirst({
      where: {
        domain: snapshot.domain,
        kind: draft.suggestedAction.kind,
        title: draft.suggestedAction.title,
      },
    })
    if (existing) continue

    const canDeploy = config.deployAccess
    const autoApply = canDeploy && config.publishingPolicy === 'auto_low_risk'

    const action = await prisma.action.create({
      data: {
        opportunityId: opportunity.id,
        domain: snapshot.domain,
        kind: draft.suggestedAction.kind,
        title: draft.suggestedAction.title,
        spec: draft.suggestedAction.spec,
        criteria: draft.suggestedAction.criteria,
        // Without deploy access an action can never honestly progress past
        // `proposed`, so it does not pretend to.
        status: autoApply ? 'approved' : 'proposed',
      },
    })
    summary.actionsCreated++
    if (!canDeploy) summary.skippedNoAccess++

    const generator = GENERATORS[draft.suggestedAction.kind]
    if (!generator) continue

    const urls = pages.filter((p) => p.status === 200).map((p) => p.url)
    const asset = generator(config, { urls })

    await prisma.asset.create({
      data: {
        actionId: action.id,
        type: asset.type,
        path: asset.path,
        body: asset.body,
        reviewState: autoApply ? 'approved' : 'in_review',
        producedBy: 'template',
        qa: { generator: draft.suggestedAction.kind },
      },
    })
    summary.assetsGenerated++
  }

  return summary
}

/**
 * Apply approved artifacts — only ever to a property we control.
 *
 * Separated from `make` on purpose: generating a fix and shipping it are
 * different permissions, and the boundary is where a portfolio-wide accident
 * would otherwise happen.
 */
export async function apply(domain: string): Promise<{ applied: string[]; refused: string[] }> {
  const config = loadProperty(domain)
  const applied: string[] = []
  const refused: string[] = []

  const actions = await prisma.action.findMany({
    where: { domain, status: { in: ['proposed', 'approved'] } },
    include: { assets: true },
  })

  for (const action of actions) {
    for (const asset of action.assets) {
      if (!config.deployAccess || !config.localSite || !asset.path) {
        refused.push(`${action.title} — no deploy access for ${domain}`)
        continue
      }

      writeFileSync(join(process.cwd(), config.localSite.dir, asset.path), asset.body)
      await prisma.asset.update({ where: { id: asset.id }, data: { reviewState: 'applied' } })
      await prisma.action.update({ where: { id: action.id }, data: { status: 'executed' } })
      applied.push(`${asset.path} (${action.title})`)
    }
  }

  return { applied, refused }
}
