import { mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { z } from 'zod'
import { prisma } from '../db'
import { loadProperty } from './config'
import { DETECTORS } from './detectors'
import type { PropertyConfig } from '../schemas'
import { makerFor } from './makers'
import type { MakerContext } from './makers/types'
import { getProvider } from './llm'

/**
 * The make stage: turn scored opportunities into actions with acceptance
 * criteria, and generate the artifact each action needs.
 *
 * Two rules, both from the risk research:
 *   - generation and publication are different permissions. `review_first`
 *     properties produce drafts that wait for a human; only `auto_low_risk`
 *     properties may have reversible fixes applied automatically.
 *   - the engine never applies anything to a property it does not control
 *     (`deployAccess: false`), regardless of policy. Those actions stay
 *     `proposed` with the artifact attached for a human to ship.
 */

export interface MakeSummary {
  actionsCreated: number
  assetsGenerated: number
  applied: number
  skippedNoAccess: number
}

/** Deterministic generators. LLM-backed makers plug in at the same seam. */
const GENERATORS: Record<
  string,
  (config: PropertyConfig, context: { urls: string[] }) => { type: string; path: string; body: string }
> = {
  ship_robots_txt: (config) => ({
    type: 'technical_fix',
    path: 'robots.txt',
    body: [
      '# Generated by the Search Growth Engine.',
      '# Search and answer-engine crawlers are allowed explicitly: they are a',
      '# distinct policy surface from Googlebot, and blocking them removes the',
      '# property from AI answers without affecting classic search.',
      '',
      'User-agent: *',
      'Allow: /',
      '',
      'User-agent: OAI-SearchBot',
      'Allow: /',
      '',
      'User-agent: PerplexityBot',
      'Allow: /',
      '',
      'User-agent: Claude-SearchBot',
      'Allow: /',
      '',
      `Sitemap: https://${config.domain}/sitemap.xml`,
      '',
    ].join('\n'),
  }),

  ship_sitemap: (config, { urls }) => ({
    type: 'technical_fix',
    path: 'sitemap.xml',
    body: [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
      ...urls.map(
        (url) =>
          `  <url>\n    <loc>${url}</loc>\n    <lastmod>${new Date().toISOString().slice(0, 10)}</lastmod>\n  </url>`,
      ),
      '</urlset>',
      '',
    ].join('\n'),
  }),
}

export async function make(snapshotId: string): Promise<MakeSummary> {
  const snapshot = await prisma.snapshot.findUniqueOrThrow({ where: { id: snapshotId } })
  const config = loadProperty(snapshot.domain)

  const opportunities = await prisma.opportunity.findMany({
    where: { snapshotId },
    orderBy: { priority: 'desc' },
  })
  const pages = await prisma.page.findMany({ where: { snapshotId } })

  // Re-derive the suggested actions from the same detector run that produced
  // the opportunities, so an action can never describe work its evidence does
  // not support.
  const [evidence, clusters] = await Promise.all([
    prisma.evidence.findMany({ where: { snapshotId } }),
    prisma.queryCluster.findMany({ where: { domain: snapshot.domain } }),
  ])
  const drafts = DETECTORS.flatMap((d) => d.run({ config, evidence, pages, clusters }))

  const summary: MakeSummary = {
    actionsCreated: 0,
    assetsGenerated: 0,
    applied: 0,
    skippedNoAccess: 0,
  }

  for (const opportunity of opportunities) {
    const draft = drafts.find(
      (d) => d.title === opportunity.title && d.subject === opportunity.subject,
    )
    if (!draft) continue

    // Actions are keyed to the *finding*, not to the snapshot that observed it.
    // Opportunity rows are recreated each run (snapshots are immutable), so
    // matching on opportunityId alone would spawn a duplicate action every
    // night for a gap that has not changed — and re-open work already shipped.
    const existing = await prisma.action.findFirst({
      where: {
        domain: snapshot.domain,
        kind: draft.suggestedAction.kind,
        title: draft.suggestedAction.title,
      },
    })
    if (existing) continue

    const canDeploy = config.deployAccess
    const autoApply = canDeploy && config.publishingPolicy === 'auto_low_risk'

    const action = await prisma.action.create({
      data: {
        opportunityId: opportunity.id,
        domain: snapshot.domain,
        kind: draft.suggestedAction.kind,
        title: draft.suggestedAction.title,
        spec: draft.suggestedAction.spec,
        criteria: draft.suggestedAction.criteria,
        // Without deploy access an action can never honestly progress past
        // `proposed`, so it does not pretend to.
        status: autoApply ? 'approved' : 'proposed',
      },
    })
    summary.actionsCreated++
    if (!canDeploy) summary.skippedNoAccess++

    // Deterministic technical fixes first; then the content makers.
    const generator = GENERATORS[draft.suggestedAction.kind]
    if (generator) {
      const urls = pages.filter((p) => p.status === 200).map((p) => p.url)
      const asset = generator(config, { urls })
      await prisma.asset.create({
        data: {
          actionId: action.id,
          type: asset.type,
          path: asset.path,
          body: asset.body,
          reviewState: autoApply ? 'approved' : 'in_review',
          producedBy: 'template',
          qa: { generator: draft.suggestedAction.kind },
        },
      })
      summary.assetsGenerated++
      continue
    }

    const maker = makerFor(draft.suggestedAction.kind)
    if (!maker) continue

    const made = await maker.make(makerContext(config, draft.subject, evidence, clusters))

    await prisma.asset.create({
      data: {
        actionId: action.id,
        type: made.type,
        path: made.path,
        body: made.body,
        reviewState: autoApply ? 'approved' : 'in_review',
        producedBy: made.producedBy,
        qa: { generator: maker.kind, satisfies: made.satisfies },
      },
    })
    summary.assetsGenerated++

    // The maker chose the path, so it is the maker's output that gets checked.
    // Until now these criteria fetched the site root, which meant a perfectly
    // good generated page failed on the homepage's shortcomings.
    await prisma.action.update({
      where: { id: action.id },
      data: { criteria: scopeCriteriaTo(draft.suggestedAction.criteria, made.path) },
    })
  }

  return summary
}

/**
 * Apply approved artifacts — only ever to a property we control.
 *
 * Separated from `make` on purpose: generating a fix and shipping it are
 * different permissions, and the boundary is where a portfolio-wide accident
 * would otherwise happen.
 */
export async function apply(domain: string): Promise<{ applied: string[]; refused: string[] }> {
  const config = loadProperty(domain)
  const applied: string[] = []
  const refused: string[] = []

  const actions = await prisma.action.findMany({
    where: { domain, status: { in: ['proposed', 'approved'] } },
    include: { assets: true },
  })

  for (const action of actions) {
    for (const asset of action.assets) {
      if (!config.deployAccess || !config.localSite || !asset.path) {
        refused.push(`${action.title} — no deploy access for ${domain}`)
        continue
      }

      const target = join(process.cwd(), config.localSite.dir, asset.path)
      mkdirSync(dirname(target), { recursive: true })
      writeFileSync(target, asset.body)
      await prisma.asset.update({ where: { id: asset.id }, data: { reviewState: 'applied' } })
      await prisma.action.update({ where: { id: action.id }, data: { status: 'executed' } })
      applied.push(`${asset.path} (${action.title})`)
    }
  }

  // A sitemap is a derived artifact: it goes stale the moment new pages ship,
  // and pages nothing links to are pages nothing discovers. Re-deriving it
  // from what is actually on disk closes that gap — which is what a deploy
  // pipeline does, and why the next crawl can see the work.
  if (applied.length > 0 && config.deployAccess && config.localSite) {
    refreshSitemap(config.localSite.dir, config.domain)
    applied.push('sitemap.xml (re-derived after publish)')
  }

  return { applied, refused }
}

function refreshSitemap(dir: string, domain: string): void {
  const root = join(process.cwd(), dir)
  const pages: string[] = []

  const walk = (current: string, prefix: string) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      if (entry.isDirectory()) walk(join(current, entry.name), `${prefix}${entry.name}/`)
      else if (entry.name.endsWith('.html')) pages.push(`${prefix}${entry.name}`)
    }
  }
  walk(root, '')

  const today = new Date().toISOString().slice(0, 10)
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...pages.map(
      (p) =>
        `  <url>\n    <loc>https://${domain}/${p === 'index.html' ? '' : p}</loc>\n    <lastmod>${today}</lastmod>\n  </url>`,
    ),
    '</urlset>',
    '',
  ].join('\n')

  writeFileSync(join(root, 'sitemap.xml'), xml)
}

/**
 * Assemble what a maker is allowed to know: only evidence already collected
 * for this property. A maker that could reach outside this context could
 * assert things the engine has not observed.
 */
function makerContext(
  config: PropertyConfig,
  subject: string,
  evidence: { kind: string; subject: string; value: unknown }[],
  clusters: { query: string; intent: string; demand: number }[],
): MakerContext {
  const serp = evidence.find((e) => e.kind === 'serp_observation' && e.subject === subject)?.value as
    | { topResults?: { position: number; url: string; title: string }[] }
    | undefined

  const demandRow = evidence.find((e) => e.kind === 'demand_signal' && e.subject === subject)
    ?.value as { suggestions?: string[] } | undefined

  const cluster = clusters.find((c) => c.query === subject)
  const provider = getProvider()
  const canEnrich = provider.unavailableReason() === null

  return {
    config,
    subject,
    evidence: {
      competitors: (serp?.topResults ?? []).filter((r) => !r.url.includes(config.domain)).slice(0, 5),
      relatedQueries: demandRow?.suggestions ?? [],
      demand: cluster?.demand ?? 0,
      intent: cluster?.intent ?? 'commercial',
    },
    // Enrichment is optional by design: the asset must be publishable without
    // it, so a missing key or a provider outage degrades copy quality rather
    // than blocking the pipeline.
    enrich: canEnrich
      ? async (prompt, schemaName) => {
          try {
            const result = await provider.generateObject({
              system:
                'You write factual, plain marketing copy. No superlatives, no invented statistics, ' +
                'no claims you cannot support. Return only the requested keys.',
              prompt,
              schema: LooseCopy,
              schemaName,
            })
            return result
          } catch {
            return null
          }
        }
      : undefined,
  }
}

/** Copy comes back as free-form keys; the maker decides what it uses. */
const LooseCopy = z.record(z.string())

/** Point page-level delivery checks at the asset that was actually produced. */
function scopeCriteriaTo(
  criteria: { id: string; description: string; check: string }[],
  assetPath: string,
): { id: string; description: string; check: string }[] {
  const PAGE_SCOPED = [
    'answer_block_present',
    'internal_links_min',
    'sourced_stats',
    'schema_type_present',
    'page_indexable',
    'min_text_length',
  ]
  const target = assetPath.startsWith('/') ? assetPath : `/${assetPath}`

  return criteria.map((c) => {
    const verb = c.check.split(':')[0].split('@')[0]
    if (!PAGE_SCOPED.includes(verb) || c.check.includes('@')) return c
    return { ...c, check: `${c.check}@${target}` }
  })
}
